const API = window.__MEDI_API__ || '/api';
const app = document.getElementById('app');
const savedPrefs = JSON.parse(localStorage.getItem('medi_accessibility') || '{}');
const state = {
  user: JSON.parse(localStorage.getItem('medi_user') || 'null'),
  token: localStorage.getItem('medi_token') || '',
  role: sessionStorage.getItem('medi_role') || '',
  section: 'overview', data: {},
  lang: localStorage.getItem('medi_lang') || 'en',
  disability: savedPrefs.disability || 'none',
  voice: savedPrefs.disability === 'blind',
  motionSOS: localStorage.getItem('medi_motion_sos') !== 'off',
  sosTimer: null, sosActive: false, motionBound: false, lastShock: 0
};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const langs={
  en:{name:'English',speech:'en-IN'}, hi:{name:'हिन्दी',speech:'hi-IN'}, te:{name:'తెలుగు',speech:'te-IN'}, ta:{name:'தமிழ்',speech:'ta-IN'}
};
const T={
  en:{home:'Home',about:'About',features:'Features',services:'Services',contact:'Contact',help:'Help Center',getStarted:'Get Started',hero:'Healthcare that moves with you.',heroSub:'One intelligent platform for patients, doctors, hospitals and platform administrators.',selectRole:'Select your role',selectRoleSub:'Choose your role first. Your dedicated login will appear next.',patient:'Patient',doctor:'Doctor',hospital:'Hospital',admin:'Platform Administrator',continue:'Continue',changeRole:'Change role',login:'Login',email:'Email',password:'Password',signIn:'Sign in',access:'ACCESS',voice:'Voice Assistant',language:'Language',accessibility:'Accessibility',disability:'Accessibility support',none:'No disability',blind:'Blind / Screen reader user',lowVision:'Low vision',motor:'Motor / mobility support',blindHelp:'Blind mode automatically reads the page and enables voice commands.',motion:'Motion SOS',motionOn:'Motion SOS enabled',motionOff:'Motion SOS disabled',sos:'Emergency SOS',sosText:'Emergency alert starts a 30-second countdown. Cancel before it ends.',cancel:'Cancel Alert',sent:'Alert Sent',nearby:'Nearest authorized hospital notified',location:'Location',dashboard:'Dashboard',overview:'Overview',appointments:'Appointments',records:'Medical Records',prescriptions:'Prescriptions',profile:'My Profile',settings:'Settings',book:'Book Appointment',history:'Consultation History',today:"Today's Appointments",queue:'Patient Queue',consult:'Consultation',followup:'Follow-up Patients',doctors:'Doctors',patients:'Patients',departments:'Departments',reports:'Reports',users:'Users',hospitals:'Hospitals',emergency:'Emergency Cases',analytics:'Reports & Analytics',logout:'Logout',listening:'Listening. Tell me what you need.',voiceHint:'Try: dashboard, appointments, records, prescriptions, profile, settings, emergency.',accessSaved:'Accessibility preference saved.'},
  hi:{home:'होम',about:'परिचय',features:'विशेषताएँ',services:'सेवाएँ',contact:'संपर्क',help:'सहायता केंद्र',getStarted:'शुरू करें',hero:'स्वास्थ्य सेवा अब आपके साथ।',heroSub:'मरीज़, डॉक्टर, अस्पताल और प्लेटफ़ॉर्म प्रशासक के लिए एक स्मार्ट प्लेटफ़ॉर्म।',selectRole:'अपनी भूमिका चुनें',selectRoleSub:'पहले भूमिका चुनें। उसके बाद संबंधित लॉगिन दिखाई देगा।',patient:'मरीज़',doctor:'डॉक्टर',hospital:'अस्पताल',admin:'प्लेटफ़ॉर्म प्रशासक',continue:'जारी रखें',changeRole:'भूमिका बदलें',login:'लॉगिन',email:'ईमेल',password:'पासवर्ड',signIn:'साइन इन',access:'प्रवेश',voice:'वॉइस सहायक',language:'भाषा',accessibility:'सुलभता',disability:'सुलभता सहायता',none:'कोई विकलांगता नहीं',blind:'दृष्टिबाधित / स्क्रीन रीडर',lowVision:'कम दृष्टि',motor:'गतिशीलता सहायता',blindHelp:'ब्लाइंड मोड पेज पढ़ता है और वॉइस कमांड चालू करता है।',motion:'मोशन SOS',motionOn:'मोशन SOS चालू',motionOff:'मोशन SOS बंद',sos:'आपातकालीन SOS',sosText:'आपातकालीन अलर्ट 30 सेकंड की उलटी गिनती के बाद भेजा जाएगा।',cancel:'अलर्ट रद्द करें',sent:'अलर्ट भेजा गया',nearby:'निकटतम अधिकृत अस्पताल को सूचना भेजी गई',location:'स्थान',dashboard:'डैशबोर्ड',overview:'अवलोकन',appointments:'अपॉइंटमेंट',records:'मेडिकल रिकॉर्ड',prescriptions:'प्रिस्क्रिप्शन',profile:'मेरी प्रोफ़ाइल',settings:'सेटिंग्स',book:'अपॉइंटमेंट बुक करें',history:'परामर्श इतिहास',today:'आज के अपॉइंटमेंट',queue:'मरीज़ कतार',consult:'परामर्श',followup:'फॉलो-अप मरीज़',doctors:'डॉक्टर',patients:'मरीज़',departments:'विभाग',reports:'रिपोर्ट',users:'उपयोगकर्ता',hospitals:'अस्पताल',emergency:'आपातकालीन मामले',analytics:'रिपोर्ट और विश्लेषण',logout:'लॉगआउट',listening:'सुन रहा हूँ। बताइए आपको क्या चाहिए।',voiceHint:'कहें: डैशबोर्ड, अपॉइंटमेंट, रिकॉर्ड, प्रिस्क्रिप्शन, प्रोफ़ाइल, सेटिंग्स या आपातकाल।',accessSaved:'सुलभता पसंद सहेजी गई।'},
  te:{home:'హోమ్',about:'గురించి',features:'ఫీచర్లు',services:'సేవలు',contact:'సంప్రదించండి',help:'సహాయ కేంద్రం',getStarted:'ప్రారంభించండి',hero:'ఆరోగ్య సేవ మీతో ముందుకు.',heroSub:'రోగులు, వైద్యులు, ఆసుపత్రులు మరియు ప్లాట్‌ఫారమ్ నిర్వాహకుల కోసం స్మార్ట్ ప్లాట్‌ఫారమ్.',selectRole:'మీ పాత్రను ఎంచుకోండి',selectRoleSub:'ముందుగా పాత్రను ఎంచుకోండి. తరువాత దానికి సంబంధించిన లాగిన్ కనిపిస్తుంది.',patient:'రోగి',doctor:'వైద్యుడు',hospital:'ఆసుపత్రి',admin:'ప్లాట్‌ఫారమ్ నిర్వాహకుడు',continue:'కొనసాగించండి',changeRole:'పాత్ర మార్చండి',login:'లాగిన్',email:'ఈమెయిల్',password:'పాస్‌వర్డ్',signIn:'సైన్ ఇన్',access:'ప్రవేశం',voice:'వాయిస్ సహాయకుడు',language:'భాష',accessibility:'అందుబాటు',disability:'అందుబాటు సహాయం',none:'వైకల్యం లేదు',blind:'దృష్టి లోపం / స్క్రీన్ రీడర్',lowVision:'తక్కువ చూపు',motor:'కదలిక సహాయం',blindHelp:'బ్లైండ్ మోడ్ పేజీని చదివి వాయిస్ కమాండ్లను ప్రారంభిస్తుంది.',motion:'మోషన్ SOS',motionOn:'మోషన్ SOS ప్రారంభించబడింది',motionOff:'మోషన్ SOS నిలిపివేయబడింది',sos:'అత్యవసర SOS',sosText:'30 సెకన్ల కౌంట్‌డౌన్ తర్వాత అత్యవసర సమాచారం పంపబడుతుంది.',cancel:'అలర్ట్ రద్దు',sent:'అలర్ట్ పంపబడింది',nearby:'సమీపంలోని అధీకృత ఆసుపత్రికి సమాచారం పంపబడింది',location:'స్థానం',dashboard:'డ్యాష్‌బోర్డ్',overview:'అవలోకనం',appointments:'అపాయింట్‌మెంట్లు',records:'మెడికల్ రికార్డులు',prescriptions:'ప్రిస్క్రిప్షన్లు',profile:'నా ప్రొఫైల్',settings:'సెట్టింగ్స్',book:'అపాయింట్‌మెంట్ బుక్ చేయండి',history:'కన్సల్టేషన్ చరిత్ర',today:'ఈరోజు అపాయింట్‌మెంట్లు',queue:'రోగుల క్యూ',consult:'కన్సల్టేషన్',followup:'ఫాలో-అప్ రోగులు',doctors:'వైద్యులు',patients:'రోగులు',departments:'విభాగాలు',reports:'రిపోర్టులు',users:'యూజర్లు',hospitals:'ఆసుపత్రులు',emergency:'అత్యవసర కేసులు',analytics:'రిపోర్టులు & విశ్లేషణ',logout:'లాగ్ అవుట్',listening:'వింటున్నాను. మీకు కావలసినది చెప్పండి.',voiceHint:'డ్యాష్‌బోర్డ్, అపాయింట్‌మెంట్లు, రికార్డులు, ప్రిస్క్రిప్షన్లు, ప్రొఫైల్, సెట్టింగ్స్ లేదా అత్యవసరం అని చెప్పండి.',accessSaved:'అందుబాటు ఎంపిక సేవ్ చేయబడింది.'},
  ta:{home:'முகப்பு',about:'பற்றி',features:'அம்சங்கள்',services:'சேவைகள்',contact:'தொடர்பு',help:'உதவி மையம்',getStarted:'தொடங்குங்கள்',hero:'சுகாதாரம் உங்களுடன் நகர்கிறது.',heroSub:'நோயாளிகள், மருத்துவர்கள், மருத்துவமனைகள் மற்றும் நிர்வாகிகளுக்கான ஸ்மார்ட் தளம்.',selectRole:'உங்கள் பங்கை தேர்வு செய்யவும்',selectRoleSub:'முதலில் பங்கை தேர்வு செய்யவும். அதற்கான உள்நுழைவு அடுத்ததாக வரும்.',patient:'நோயாளர்',doctor:'மருத்துவர்',hospital:'மருத்துவமனை',admin:'தள நிர்வாகி',continue:'தொடரவும்',changeRole:'பங்கை மாற்றவும்',login:'உள்நுழைவு',email:'மின்னஞ்சல்',password:'கடவுச்சொல்',signIn:'உள்நுழைக',access:'அணுகல்',voice:'குரல் உதவியாளர்',language:'மொழி',accessibility:'அணுகல்தன்மை',disability:'அணுகல் உதவி',none:'இயலாமை இல்லை',blind:'பார்வையற்றவர் / ஸ்கிரீன் ரீடர்',lowVision:'குறைந்த பார்வை',motor:'இயக்கம் உதவி',blindHelp:'பார்வையற்றவர் பயன்முறை பக்கத்தை வாசித்து குரல் கட்டளைகளை இயக்கும்.',motion:'மோஷன் SOS',motionOn:'மோஷன் SOS இயக்கப்பட்டது',motionOff:'மோஷன் SOS முடக்கப்பட்டது',sos:'அவசர SOS',sosText:'30 விநாடி கவுண்ட்டவுனுக்குப் பிறகு அவசர தகவல் அனுப்பப்படும்.',cancel:'அலர்ட்டை ரத்து செய்',sent:'அலர்ட் அனுப்பப்பட்டது',nearby:'அருகிலுள்ள அங்கீகரிக்கப்பட்ட மருத்துவமனைக்கு தகவல் அனுப்பப்பட்டது',location:'இருப்பிடம்',dashboard:'டாஷ்போர்டு',overview:'மேலோட்டம்',appointments:'அப்பாயிண்ட்மெண்ட்கள்',records:'மருத்துவ பதிவுகள்',prescriptions:'மருந்துச் சீட்டுகள்',profile:'என் சுயவிவரம்',settings:'அமைப்புகள்',book:'அப்பாயிண்ட்மெண்ட் பதிவு',history:'ஆலோசனை வரலாறு',today:'இன்றைய அப்பாயிண்ட்மெண்ட்கள்',queue:'நோயாளர் வரிசை',consult:'ஆலோசனை',followup:'தொடர் நோயாளிகள்',doctors:'மருத்துவர்கள்',patients:'நோயாளிகள்',departments:'துறைகள்',reports:'அறிக்கைகள்',users:'பயனர்கள்',hospitals:'மருத்துவமனைகள்',emergency:'அவசர வழக்குகள்',analytics:'அறிக்கைகள் & பகுப்பாய்வு',logout:'வெளியேறு',listening:'கேட்கிறேன். உங்களுக்கு என்ன வேண்டும் என்று சொல்லுங்கள்.',voiceHint:'டாஷ்போர்டு, அப்பாயிண்ட்மெண்ட், பதிவுகள், மருந்துச் சீட்டுகள், சுயவிவரம், அமைப்புகள் அல்லது அவசரம் என்று சொல்லுங்கள்.',accessSaved:'அணுகல் விருப்பம் சேமிக்கப்பட்டது.'}
};
const t=k=>(T[state.lang]&&T[state.lang][k])||T.en[k]||k;
const roles={patient:{titleKey:'patient',icon:'🧑‍🦽',desc:'Appointments, records, prescriptions and emergency support.'},doctor:{titleKey:'doctor',icon:'🩺',desc:'Schedule, patient queue, consultations and prescriptions.'},hospital:{titleKey:'hospital',icon:'🏥',desc:'Doctors, patients, departments, appointments and emergencies.'},admin:{titleKey:'admin',icon:'🛡️',desc:'Platform users, hospitals, analytics and emergency monitoring.'}};
const api=async(path,opt={})=>{const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(state.token?{Authorization:`Bearer ${state.token}`}:{})}});const d=await r.json().catch(()=>({message:'Server response error'}));if(!r.ok)throw Error(d.message||'Request failed');return d};
const save=()=>{localStorage.setItem('medi_user',JSON.stringify(state.user));localStorage.setItem('medi_token',state.token)};
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=langs[state.lang].speech;u.rate=state.disability==='blind'?0.95:1;speechSynthesis.speak(u)}
function setLang(lang){if(!langs[lang])return;state.lang=lang;localStorage.setItem('medi_lang',lang);document.documentElement.lang=lang;render();if(state.disability==='blind')setTimeout(()=>speak(document.body.innerText.slice(0,1100)),250)}
function setDisability(value){state.disability=value;state.voice=value==='blind';localStorage.setItem('medi_accessibility',JSON.stringify({disability:value}));document.body.classList.toggle('blind-mode',value==='blind');document.body.classList.toggle('low-vision',value==='lowVision');document.body.classList.toggle('motor-mode',value==='motor');render(false);speak(t('accessSaved'));if(value==='blind')setTimeout(()=>speak(document.body.innerText.slice(0,1100)),300)}
function langControls(){return `<div class="access-tools"><label class="select-tool"><span>🌐 ${t('language')}</span><select id="language-select" aria-label="${t('language')}">${Object.entries(langs).map(([k,v])=>`<option value="${k}" ${state.lang===k?'selected':''}>${v.name}</option>`).join('')}</select></label><label class="select-tool"><span>♿ ${t('accessibility')}</span><select id="disability-select" aria-label="${t('disability')}"><option value="none" ${state.disability==='none'?'selected':''}>${t('none')}</option><option value="blind" ${state.disability==='blind'?'selected':''}>${t('blind')}</option><option value="lowVision" ${state.disability==='lowVision'?'selected':''}>${t('lowVision')}</option><option value="motor" ${state.disability==='motor'?'selected':''}>${t('motor')}</option></select></label></div>`}
function header(){return `<header class="topbar"><button class="brand" data-action="home" aria-label="Medi Smart Home">✦ MEDI<span>SMART</span></button><div class="top-tools">${langControls()}<button class="glass-btn" data-action="voice" aria-label="${t('voice')}">🎙 ${t('voice')}</button>${state.user?`<span class="user-chip">${esc(state.user.name)} · ${t(state.user.role)}</span><button class="glass-btn" data-action="logout">${t('logout')}</button>`:''}</div></header>`}
function home(){return `${header()}<main class="home"><section class="hero"><div class="hero-copy"><div class="eyebrow">AI • ${t('accessibility').toUpperCase()} • SOS</div><h1>${t('hero')}</h1><p>${t('heroSub')}</p><button class="primary big" data-action="roles">${t('getStarted')} <b>→</b></button><div class="trust"><span>● ${t('accessibility')}</span><span>● ${t('voice')}</span><span>● ${t('sos')}</span></div></div><div class="scene" aria-hidden="true"><div class="orb orb-a"></div><div class="orb orb-b"></div><div class="orb orb-c"></div><div class="ring ring-a"></div><div class="ring ring-b"></div><div class="ring ring-c"></div><div class="heart">✚</div><div class="float-card card-a">❤️ <b>24/7</b><small>Emergency Ready</small></div><div class="float-card card-b">🧠 <b>Smart Care</b><small>Connected records</small></div><div class="float-card card-c">🎙️ <b>Voice AI</b><small>Hands-free control</small></div><div class="holo">MEDI<br>SMART</div></div></section><section class="feature-grid"><article><b>01</b><h3>${t('selectRole')}</h3><p>${t('selectRoleSub')}</p></article><article><b>02</b><h3>4 Languages</h3><p>English • తెలుగు • हिन्दी • தமிழ்</p></article><article><b>03</b><h3>${t('sos')}</h3><p>${t('sosText')}</p></article></section></main>`}
function rolesPage(){return `${header()}<main class="center-page"><div class="section-head"><div class="eyebrow">SECURE • ACCESSIBLE • MULTILINGUAL</div><h1>${t('selectRole')}</h1><p>${t('selectRoleSub')}</p></div><section class="access-panel"><div><h2>♿ ${t('accessibility')}</h2><p>${t('blindHelp')}</p></div><select id="disability-page"><option value="none">${t('none')}</option><option value="blind">${t('blind')}</option><option value="lowVision">${t('lowVision')}</option><option value="motor">${t('motor')}</option></select></section><div class="role-grid">${Object.entries(roles).map(([k,r])=>`<button class="role-card" data-role="${k}" aria-label="${t(r.titleKey)}"><div class="role-icon">${r.icon}</div><h2>${t(r.titleKey)}</h2><p>${r.desc}</p><span>${t('continue')} →</span></button>`).join('')}</div></main>`}
function demoFor(role){return ({patient:'patient@medismart.local / Patient@123',doctor:'doctor@medismart.local / Doctor@123',hospital:'hospital@medismart.local / Hospital@123',admin:'admin@medismart.local / Admin@123'})[role]}
function login(){const r=roles[state.role];return `${header()}<main class="center-page"><div class="login-card"><button class="back" data-action="roles">← ${t('changeRole')}</button><div class="role-icon">${r.icon}</div><div class="eyebrow">${t(r.titleKey).toUpperCase()} ${t('access')}</div><h1>${t(r.titleKey)} ${t('login')}</h1><p>${r.desc}</p><div id="error" aria-live="assertive"></div><form id="login-form"><label>${t('email')}<input id="email" type="email" required autocomplete="username"></label><label>${t('password')}<input id="password" type="password" required autocomplete="current-password"></label><button class="primary" type="submit">${t('signIn')} →</button></form><div class="demo">Demo: ${demoFor(state.role)}</div></div></main>`}
const patientNav=[['overview','overview'],['book','book'],['appointments','appointments'],['history','history'],['records','records'],['prescriptions','prescriptions'],['profile','profile'],['settings','settings']];
const doctorNav=[['overview','overview'],['today','today'],['queue','queue'],['consult','consult'],['records','records'],['prescriptions','prescriptions'],['followup','followup'],['profile','profile'],['settings','settings']];
const hospitalNav=[['overview','overview'],['doctors','doctors'],['patients','patients'],['appointments','appointments'],['departments','departments'],['emergency','emergency'],['reports','reports'],['profile','profile'],['settings','settings']];
const adminNav=[['overview','overview'],['users','users'],['patients','patients'],['doctors','doctors'],['hospitals','hospitals'],['appointments','appointments'],['records','records'],['prescriptions','prescriptions'],['emergency','emergency'],['reports','analytics'],['settings','settings']];
function nav(){const n={patient:patientNav,doctor:doctorNav,hospital:hospitalNav,admin:adminNav}[state.user.role];return `<aside class="side"><div class="side-role">${roles[state.user.role].icon}<span>${t(roles[state.user.role].titleKey)}</span></div>${n.map(([k,label])=>`<button class="side-item ${state.section===k?'active':''}" data-section="${k}">${t(label)}</button>`).join('')}<button class="side-item sos-link" data-action="sos">🚨 ${t('sos')}</button>${state.user.role==='patient'?`<button class="side-item motion-link" data-action="motion">📳 ${state.motionSOS?t('motionOn'):t('motionOff')}</button>`:''}</aside>`}
function card(title,value,sub,icon){return `<div class="metric"><div class="metric-icon">${icon}</div><div><strong>${esc(value)}</strong><span>${title}</span><small>${sub||''}</small></div></div>`}
function table(title,headers,rows){return `<section class="panel"><div class="panel-head"><h2>${title}</h2></div><div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="empty">No data available</td></tr>`}</tbody></table></div></section>`}
function patientContent(){const d=state.data;switch(state.section){case'book':return `<section class="panel"><h2>${t('book')}</h2><form id="book-form" class="form-grid"><label>Doctor<select id="doctor" required>${(d.doctors||[]).map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.specialization||x.department)}</option>`).join('')}</select></label><label>Department<input id="department" required value="${esc(d.doctors?.[0]?.department||'General Medicine')}"></label><label>Date<input id="date" type="date" required></label><label>Time<input id="time" type="time" required></label><label class="wide">Reason<textarea id="reason" required></textarea></label><button class="primary" type="submit">${t('book')}</button></form></section>`;case'appointments':return table(t('appointments'),['Doctor','Date','Time','Department','Status'],(d.appointments||[]).map(a=>`<tr><td>${esc(a.doctor?.name)}</td><td>${a.date}</td><td>${a.time}</td><td>${esc(a.department)}</td><td>${a.status}</td></tr>`));case'history':return table(t('history'),['Date','Doctor','Diagnosis','Treatment'],(d.appointments||[]).filter(a=>a.status==='completed').map(a=>`<tr><td>${a.date}</td><td>${esc(a.doctor?.name)}</td><td>${esc(a.diagnosis||'—')}</td><td>${esc(a.treatmentNotes||'—')}</td></tr>`));case'records':return table(t('records'),['Title','Type','Date','Uploaded By'],(d.records||[]).map(r=>`<tr><td>${esc(r.title)}</td><td>${esc(r.type)}</td><td>${esc(r.date)}</td><td>${esc(r.uploadedByUser?.name)}</td></tr>`));case'prescriptions':return table(t('prescriptions'),['Doctor','Date','Medicines','Instructions'],(d.prescriptions||[]).map(p=>`<tr><td>${esc(p.doctor?.name)}</td><td>${esc(p.date?.slice(0,10))}</td><td>${p.medicines.map(m=>esc(m.name)).join(', ')}</td><td>${esc(p.instructions)}</td></tr>`));default:return `<div class="metrics">${card(t('appointments'),d.appointments?.length||0,'Scheduled visits','📅')}${card(t('prescriptions'),d.prescriptions?.length||0,'Digital prescriptions','💊')}${card(t('records'),d.records?.length||0,'Secure records','📄')}${card('Health ID',state.user.qrHealthId||'MEDI-ID','QR identity','▦')}</div><div class="split"><section class="panel"><h2>${t('appointments')}</h2>${(d.appointments||[]).slice(0,3).map(a=>`<div class="list-row"><b>${esc(a.doctor?.name)}</b><span>${a.date} · ${a.time}</span><em>${a.status}</em></div>`).join('')||'<p class="empty">No upcoming appointments.</p>'}</section><section class="panel sos-panel"><h2>${t('sos')}</h2><p>${t('sosText')}</p><button class="danger" data-action="sos">🚨 ${t('sos')}</button></section></div>`}}
function doctorContent(){const d=state.data;switch(state.section){case'today':return table(t('today'),['Patient','Time','Department','Status','Action'],(d.appointments||[]).map(a=>`<tr><td>${esc(a.patient?.name)}</td><td>${a.time}</td><td>${esc(a.department)}</td><td>${a.status}</td><td><button class="mini" data-appt="${a.id}" data-status="confirmed">Confirm</button> <button class="mini" data-appt="${a.id}" data-status="completed">Complete</button></td></tr>`));case'queue':return table(t('queue'),['Patient','Time','Status'],(d.appointments||[]).filter(a=>['pending','confirmed'].includes(a.status)).map(a=>`<tr><td>${esc(a.patient?.name)}</td><td>${a.time}</td><td>${a.status}</td></tr>`));case'consult':return `<section class="panel"><h2>${t('consult')}</h2><form id="consult-form" class="form-grid"><label>Appointment<select id="consult-appt" required>${(d.appointments||[]).map(a=>`<option value="${a.id}">${esc(a.patient?.name)} · ${a.date} ${a.time}</option>`).join('')}</select></label><label class="wide">Diagnosis<textarea id="diagnosis" required></textarea></label><label class="wide">Treatment Notes<textarea id="treatment" required></textarea></label><button class="primary" type="submit">Complete Consultation</button></form></section>`;case'records':return table(t('records'),['Patient','Title','Type','Date'],(d.records||[]).map(r=>`<tr><td>${esc(r.patient?.name)}</td><td>${esc(r.title)}</td><td>${esc(r.type)}</td><td>${r.date}</td></tr>`));case'prescriptions':return `<section class="panel"><h2>${t('prescriptions')}</h2><form id="rx-form" class="form-grid"><label>Patient<select id="rx-patient" required>${[...new Map((d.appointments||[]).map(a=>[a.patientId,a.patient])).values()].map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>Medicine<input id="rx-med" required></label><label>Dosage<input id="rx-dose" required></label><label>Frequency<input id="rx-freq" required></label><label>Duration<input id="rx-duration" required></label><label class="wide">Instructions<textarea id="rx-instructions"></textarea></label><button class="primary" type="submit">Issue Prescription</button></form></section>`;default:return `<div class="metrics">${card(t('today'),d.appointments?.filter(a=>a.date===new Date().toISOString().slice(0,10)).length||0,'Schedule','📅')}${card('Patients',new Set((d.appointments||[]).map(a=>a.patientId)).size,'Connected patients','👥')}${card('Emergency Cases',0,'Hospital alerts','🚨')}${card(t('followup'),(d.appointments||[]).filter(a=>a.status==='confirmed').length,'Upcoming visits','🔁')}</div>${table(t('today'),['Patient','Date','Time','Status'],(d.appointments||[]).slice(0,6).map(a=>`<tr><td>${esc(a.patient?.name)}</td><td>${a.date}</td><td>${a.time}</td><td>${a.status}</td></tr>`))}`}}
function hospitalContent(){const d=state.data;switch(state.section){case'doctors':return table(t('doctors'),['Name','Specialization','Department','Status'],(d.doctors||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.specialization)}</td><td>${esc(x.department)}</td><td>${x.active?'Active':'Inactive'}</td></tr>`));case'patients':return table(t('patients'),['Name','Email','Phone'],(d.patients||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${esc(x.phone)}</td></tr>`));case'appointments':return table(t('appointments'),['Patient','Doctor','Date','Status'],(d.appointments||[]).map(a=>`<tr><td>${esc(a.patient?.name)}</td><td>${esc(a.doctor?.name)}</td><td>${a.date}</td><td>${a.status}</td></tr>`));case'emergency':return table(t('emergency'),['Patient','Created','Location','Nearest Hospital','Status'],(d.emergencies||[]).map(e=>`<tr><td>${esc(e.patient?.name)}</td><td>${e.createdAt?.slice(0,19).replace('T',' ')}</td><td>${e.latitude?`${e.latitude}, ${e.longitude}`:'Unavailable'}</td><td>${esc(e.nearestHospital?.name||'—')}</td><td>${esc(e.status)}</td></tr>`));default:return `<div class="metrics">${card(t('doctors'),d.doctors?.length||0,'Hospital doctors','🩺')}${card(t('patients'),d.patients?.length||0,'Connected patients','👥')}${card(t('appointments'),d.appointments?.length||0,'Hospital appointments','📅')}${card(t('emergency'),d.emergencies?.length||0,'Alerts','🚨')}</div>${table(t('appointments'),['Patient','Doctor','Date','Status'],(d.appointments||[]).slice(0,6).map(a=>`<tr><td>${esc(a.patient?.name)}</td><td>${esc(a.doctor?.name)}</td><td>${a.date}</td><td>${a.status}</td></tr>`))}`}}
function adminContent(){const d=state.data;switch(state.section){case'users':return table(t('users'),['Name','Email','Role','Status'],(d.users||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${t(x.role)}</td><td>${x.active?'Active':'Inactive'}</td></tr>`));case'patients':return table(t('patients'),['Name','Email','Phone','Created'],(d.patients||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${esc(x.phone)}</td><td>${x.createdAt?.slice(0,10)}</td></tr>`));case'doctors':return table(t('doctors'),['Name','Specialization','Hospital','Status'],(d.doctors||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.specialization)}</td><td>${esc(x.hospitalName)}</td><td>${x.active?'Active':'Inactive'}</td></tr>`));case'hospitals':return table(t('hospitals'),['Name','Email','Address','Status'],(d.hospitals||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${esc(x.address)}</td><td>${x.active?'Active':'Inactive'}</td></tr>`));case'emergency':return table(t('emergency'),['Patient','Created','Location','Nearest Hospital','Status'],(d.emergencies||[]).map(e=>`<tr><td>${esc(e.patient?.name)}</td><td>${e.createdAt?.slice(0,19).replace('T',' ')}</td><td>${e.latitude?`${e.latitude}, ${e.longitude}`:'Unavailable'}</td><td>${esc(e.nearestHospital?.name||'—')}</td><td>${e.status}</td></tr>`));default:return `<div class="metrics">${card(t('users'),d.users?.length||0,'All roles','👥')}${card(t('doctors'),d.doctors?.length||0,'Platform doctors','🩺')}${card(t('hospitals'),d.hospitals?.length||0,'Connected hospitals','🏥')}${card('Emergency Alerts',d.emergencies?.length||0,'Monitored events','🚨')}</div>${table(t('users'),['Name','Role','Email'],(d.users||[]).slice(0,8).map(x=>`<tr><td>${esc(x.name)}</td><td>${t(x.role)}</td><td>${esc(x.email)}</td></tr>`))}`}}
function dashboard(){return `${header()}<div class="dash"><nav>${nav()}</nav><main class="dash-main"><div class="dash-head"><div><div class="eyebrow">${t(roles[state.user.role].titleKey).toUpperCase()} ${t('dashboard').toUpperCase()}</div><h1>Welcome, ${esc(state.user.name.split(' ')[0])}</h1></div><div class="dash-actions"><button class="glass-btn" data-action="voice">🎙 ${t('voice')}</button><button class="danger" data-action="sos">🚨 ${t('sos')}</button></div></div>${state.user.role==='patient'?patientContent():state.user.role==='doctor'?doctorContent():state.user.role==='hospital'?hospitalContent():adminContent()}</main></div>`}
async function load(){if(!state.user||!state.token)return;const r=state.user.role;try{if(r==='patient'){const [appointments,records,prescriptions,doctors]=await Promise.all([api('/appointments/my'),api('/records'),api('/prescriptions'),api('/doctors')]);state.data={appointments,records,prescriptions,doctors}}else if(r==='doctor'){const [appointments,records,prescriptions]=await Promise.all([api('/appointments/doctor'),api('/records'),api('/prescriptions')]);state.data={appointments,records,prescriptions}}else if(r==='hospital'){const [appointments,doctors,patients,emergencies]=await Promise.all([api('/appointments'),api('/hospital/doctors'),api('/hospital/patients'),api('/emergency')]);state.data={appointments,doctors,patients,emergencies}}else{const [users,patients,doctors,hospitals,appointments,records,prescriptions,emergencies]=await Promise.all([api('/admin/users'),api('/admin/patients'),api('/admin/doctors'),api('/admin/hospitals'),api('/admin/appointments'),api('/admin/records'),api('/admin/prescriptions'),api('/emergency')]);state.data={users,patients,doctors,hospitals,appointments,records,prescriptions,emergencies}}}catch(e){console.error(e)}render(false);if(state.disability==='blind')setTimeout(()=>speak(document.body.innerText.slice(0,1300)),250);bindMotion()}
async function doLogin(form){try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email:form.email.value,password:form.password.value,role:state.role})});state.user=d.user;state.token=d.token;save();state.section='overview';await load()}catch(e){document.getElementById('error').innerHTML=`<div class="error" role="alert">${esc(e.message)}</div>`;speak(e.message)}}
async function doBook(form){try{await api('/appointments',{method:'POST',body:JSON.stringify({doctor:form.doctor.value,department:form.department.value,date:form.date.value,time:form.time.value,reason:form.reason.value})});await load()}catch(e){alert(e.message)}}
async function doConsult(form){try{await api(`/appointments/${form['consult-appt'].value}/status`,{method:'PUT',body:JSON.stringify({status:'completed',diagnosis:form.diagnosis.value,treatmentNotes:form.treatment.value})});await load()}catch(e){alert(e.message)}}
async function doRx(form){try{await api('/prescriptions',{method:'POST',body:JSON.stringify({patientId:form['rx-patient'].value,appointmentId:'',medicines:[{name:form['rx-med'].value,dosage:form['rx-dose'].value,frequency:form['rx-freq'].value,duration:form['rx-duration'].value}],instructions:form['rx-instructions'].value})});await load()}catch(e){alert(e.message)}}
async function updateAppt(id,status){try{await api(`/appointments/${id}/status`,{method:'PUT',body:JSON.stringify({status})});await load()}catch(e){alert(e.message)}}
function loudAlert(){try{const C=window.AudioContext||window.webkitAudioContext;if(C){const c=new C(),o=c.createOscillator(),g=c.createGain();o.type='square';o.frequency.value=880;g.gain.value=.12;o.connect(g);g.connect(c.destination);o.start();const stop=()=>{o.stop();c.close()};setTimeout(stop,700)}}catch{} }
async function getLocation(){if(!navigator.geolocation)throw Error('Location is not supported by this device.');return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}),reject,{enableHighAccuracy:true,timeout:9000,maximumAge:0}))}
async function sos(trigger='manual-sos'){if(state.sosActive)return;state.sosActive=true;let remaining=30;const overlay=document.createElement('div');overlay.className='sos-overlay';overlay.setAttribute('role','alertdialog');overlay.setAttribute('aria-modal','true');overlay.innerHTML=`<div class="sos-modal"><div class="sos-pulse">🚨</div><h1>${t('sos')}</h1><p>${t('sosText')}</p><div class="countdown" id="sos-count">30</div><p id="sos-status">${t('cancel')} before the timer reaches zero.</p><button class="cancel-sos" id="cancel-sos">${t('cancel')}</button></div>`;document.body.appendChild(overlay);speak(`${t('sos')}. ${t('sosText')}`);loudAlert();const cancel=()=>{clearInterval(state.sosTimer);state.sosActive=false;overlay.remove();speak(t('cancel'))};document.getElementById('cancel-sos').onclick=cancel;state.sosTimer=setInterval(async()=>{remaining--;document.getElementById('sos-count').textContent=remaining;loudAlert();if(remaining<=0){clearInterval(state.sosTimer);document.getElementById('sos-status').textContent='Sending your location to the nearest authorized hospital...';let loc={latitude:null,longitude:null,accuracy:null};try{loc=await getLocation();}catch(e){console.warn('Location failed',e);}try{const result=await api('/emergency',{method:'POST',body:JSON.stringify({trigger,...loc})});overlay.querySelector('.sos-modal').innerHTML=`<div class="sos-pulse">✓</div><h1>${t('sent')}</h1><p>${t('nearby')}.</p><p><b>${esc(result.nearestHospital?.name||'Hospital network')}</b></p><p>${t('location')}: ${loc.latitude?loc.latitude.toFixed(5)+', '+loc.longitude.toFixed(5):'Unavailable'}</p><button class="primary" id="close-sos">Close</button>`;document.getElementById('close-sos').onclick=()=>{overlay.remove();state.sosActive=false};speak(`${t('sent')}. ${t('nearby')}.`)}catch(e){overlay.querySelector('.sos-modal').innerHTML=`<h1>Alert could not be sent</h1><p>${esc(e.message)}</p><button class="primary" id="close-sos">Close</button>`;document.getElementById('close-sos').onclick=()=>{overlay.remove();state.sosActive=false};speak(e.message)}}},1000)}
function enableMotion(){state.motionSOS=!state.motionSOS;localStorage.setItem('medi_motion_sos',state.motionSOS?'on':'off');if(state.motionSOS)requestMotionPermission();render(false);bindMotion()}
async function requestMotionPermission(){try{if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function'){const p=await DeviceMotionEvent.requestPermission();if(p!=='granted'){state.motionSOS=false;localStorage.setItem('medi_motion_sos','off')}}}catch{}};
function bindMotion(){if(state.motionBound||!state.user||state.user.role!=='patient')return;state.motionBound=true;window.addEventListener('devicemotion',e=>{if(!state.motionSOS||state.sosActive)return;const a=e.accelerationIncludingGravity||e.acceleration;if(!a)return;const mag=Math.sqrt((a.x||0)**2+(a.y||0)**2+(a.z||0)**2);if(mag>25&&Date.now()-state.lastShock>15000){state.lastShock=Date.now();speak(t('sos'));sos('motion-shock')}})}
function voice(){if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window)){alert('Voice commands are not supported here. Use Chrome or Edge.');return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;const r=new R();r.lang=langs[state.lang].speech;r.interimResults=false;r.maxAlternatives=3;speak(t('listening')+' '+t('voiceHint'));r.onresult=e=>{const q=e.results[0][0].transcript.toLowerCase();const hit=(...words)=>words.some(w=>q.includes(w));if(hit('emergency','sos','आपात','आपत्कालीन','అత్యవసర','అత్యవసరం','அவசர'))return sos('voice-command');if(!state.user){if(hit('dashboard','डैशबोर्ड','డ్యాష్‌బోర్డ్','டாஷ்போர்டு')){location.hash='roles';return render()}return speak(t('voiceHint'))}if(hit('dashboard','overview','डैशबोर्ड','అవలోకనం','டாஷ்போர்டு'))state.section='overview';else if(hit('appointment','अपॉइंटमेंट','అపాయింట్','அப்பாயிண்ட்'))state.section=state.user.role==='patient'?'appointments':'today';else if(hit('record','रिकॉर्ड','రికార్డు','பதிவு'))state.section='records';else if(hit('prescription','प्रिस्क्रिप्शन','ప్రిస్క్రిప్షన్','மருந்து'))state.section='prescriptions';else if(hit('profile','प्रोफ़ाइल','ప్రొఫైల్','சுயவிவரம்'))state.section='profile';else if(hit('setting','सेटिंग','సెట్టింగ్','அமைப்பு'))state.section='settings';else if(hit('book','बुक','బుక్','பதிவு'))state.section='book';else speak(t('voiceHint'));render();speak(`${t(state.section)}`)};r.onerror=()=>speak('Voice command could not be completed.');r.start()}
function render(scroll=true){document.documentElement.lang=state.lang;document.body.classList.toggle('blind-mode',state.disability==='blind');document.body.classList.toggle('low-vision',state.disability==='lowVision');document.body.classList.toggle('motor-mode',state.disability==='motor');if(state.user)app.innerHTML=dashboard();else if(state.role)app.innerHTML=login();else if(location.hash==='#roles')app.innerHTML=rolesPage();else app.innerHTML=home();bind();mountPointerFX();if(scroll)window.scrollTo(0,0);if(state.disability==='blind'&&document.activeElement===document.body)setTimeout(()=>speak(document.body.innerText.slice(0,1000)),150)}
function bind(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='roles'){state.role='';sessionStorage.removeItem('medi_role');location.hash='roles';render()}else if(a==='home'){location.hash='';state.role='';render()}else if(a==='logout'){state.user=null;state.token='';state.role='';localStorage.removeItem('medi_user');localStorage.removeItem('medi_token');sessionStorage.removeItem('medi_role');location.hash='';render()}else if(a==='voice')voice();else if(a==='sos')sos();else if(a==='motion')enableMotion()});document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{state.role=b.dataset.role;sessionStorage.setItem('medi_role',state.role);location.hash='login';render();if(state.disability==='blind')setTimeout(()=>speak(`${t(state.role)} ${t('login')}`),200)});document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{state.section=b.dataset.section;render();if(state.disability==='blind')speak(t(state.section))});const ls=document.getElementById('language-select');if(ls)ls.onchange=e=>setLang(e.target.value);const ds=document.getElementById('disability-select');if(ds)ds.onchange=e=>setDisability(e.target.value);const dp=document.getElementById('disability-page');if(dp){dp.value=state.disability;dp.onchange=e=>setDisability(e.target.value)}const lf=document.getElementById('login-form');if(lf)lf.onsubmit=e=>{e.preventDefault();doLogin(lf)};const bf=document.getElementById('book-form');if(bf)bf.onsubmit=e=>{e.preventDefault();doBook(bf)};const cf=document.getElementById('consult-form');if(cf)cf.onsubmit=e=>{e.preventDefault();doConsult(cf)};const rx=document.getElementById('rx-form');if(rx)rx.onsubmit=e=>{e.preventDefault();doRx(rx)};document.querySelectorAll('[data-appt]').forEach(b=>b.onclick=()=>updateAppt(b.dataset.appt,b.dataset.status));if(state.user)bindMotion()}

function mountVisualFX(){
  if(document.getElementById('fx-canvas')) return;
  const canvas=document.createElement('canvas');
  canvas.id='fx-canvas';
  canvas.setAttribute('aria-hidden','true');
  document.body.prepend(canvas);
  const ctx=canvas.getContext('2d',{alpha:true}); if(!ctx) return;
  let W=0,H=0,DPR=1,raf=0,last=performance.now(),time=0;
  let pointer={x:.5,y:.35,tx:.5,ty:.35};
  const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const isCoarse=matchMedia('(pointer:coarse)').matches;
  const N=reduce?35:(isCoarse?70:125);
  const pts=Array.from({length:N},()=>({
    x:(Math.random()-.5)*2.5,y:(Math.random()-.5)*1.8,z:Math.random()*2.8+.2,
    vx:(Math.random()-.5)*.002,vy:(Math.random()-.5)*.002,vz:(Math.random()-.5)*.0015,
    size:Math.random()*2+.45,phase:Math.random()*Math.PI*2
  }));
  const pulses=Array.from({length:12},()=>({a:Math.random()*Math.PI*2,r:.18+Math.random()*.95,s:.0015+Math.random()*.002}));
  const resize=()=>{
    DPR=Math.min(devicePixelRatio||1,2); W=innerWidth; H=innerHeight;
    canvas.width=Math.floor(W*DPR); canvas.height=Math.floor(H*DPR);
    canvas.style.width=W+'px'; canvas.style.height=H+'px';
    ctx.setTransform(DPR,0,0,DPR,0,0);
  };
  const onPointer=e=>{pointer.tx=e.clientX/W;pointer.ty=e.clientY/H;};
  addEventListener('resize',resize,{passive:true});
  addEventListener('pointermove',onPointer,{passive:true});
  resize();
  const project=p=>{
    const z=p.z+.001, f=Math.min(W,H)*.42/z;
    return {x:W/2+p.x*f+(pointer.x-.5)*28, y:H*.52+p.y*f+(pointer.y-.5)*18, s:Math.max(.25,1.9/z)};
  };
  const drawGrid=()=>{
    ctx.save(); ctx.globalAlpha=.12; ctx.strokeStyle='rgba(67,220,208,.35)'; ctx.lineWidth=.6;
    const horizon=H*.57;
    for(let i=-10;i<=10;i++){
      const x=W/2+i*(W/14); ctx.beginPath(); ctx.moveTo(W/2+(x-W/2)*.05,horizon); ctx.lineTo(x,H); ctx.stroke();
    }
    for(let j=0;j<9;j++){
      const t=j/8, y=horizon+Math.pow(t,1.8)*(H-horizon);
      ctx.beginPath(); ctx.moveTo(0,y); ctx.lineTo(W,y); ctx.stroke();
    }
    ctx.restore();
  };
  const draw=now=>{
    const dt=Math.min(32,now-last); last=now; time+=dt*.001;
    pointer.x+=(pointer.tx-pointer.x)*.055; pointer.y+=(pointer.ty-pointer.y)*.055;
    ctx.clearRect(0,0,W,H);
    const bg=ctx.createRadialGradient(W*(.5+(.5-pointer.x)*.18),H*.18,0,W*.5,H*.35,Math.max(W,H)*.85);
    bg.addColorStop(0,'rgba(32,218,205,.10)'); bg.addColorStop(.35,'rgba(62,91,255,.035)'); bg.addColorStop(1,'rgba(3,10,20,0)');
    ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);
    if(!reduce) drawGrid();
    const projected=[];
    for(const p of pts){
      p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;
      p.x+=Math.sin(time*.35+p.phase)*.00045*dt;
      if(p.x>1.35)p.x=-1.35;if(p.x<-1.35)p.x=1.35;if(p.y>1)p.y=-1;if(p.y<-1)p.y=1;if(p.z>3)p.z=.2;if(p.z<.18)p.z=3;
      projected.push({...project(p),p});
    }
    projected.sort((a,b)=>b.p.z-a.p.z);
    for(let i=0;i<projected.length;i++){
      const a=projected[i];
      for(let j=i+1;j<Math.min(i+7,projected.length);j++){
        const b=projected[j]; const dx=a.x-b.x,dy=a.y-b.y,d=Math.hypot(dx,dy);
        if(d<115){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=`rgba(61,218,207,${(1-d/115)*.11})`;ctx.lineWidth=.55;ctx.stroke();}
      }
      const glow=ctx.createRadialGradient(a.x,a.y,0,a.x,a.y,12*a.s);
      glow.addColorStop(0,`rgba(137,255,244,${.35*a.s})`);glow.addColorStop(1,'rgba(137,255,244,0)');
      ctx.fillStyle=glow;ctx.beginPath();ctx.arc(a.x,a.y,12*a.s,0,Math.PI*2);ctx.fill();
      ctx.fillStyle=`rgba(160,255,247,${Math.min(.8,.2+a.s*.3)})`;ctx.beginPath();ctx.arc(a.x,a.y,a.p.size*a.s,0,Math.PI*2);ctx.fill();
    }
    if(!reduce){
      ctx.save();ctx.translate(W/2,H*.52);ctx.rotate(time*.025);
      for(let layer=0;layer<3;layer++){
        const radius=Math.min(W,H)*(.18+layer*.055), tilt=.28+layer*.12;
        ctx.save();ctx.scale(1,tilt);ctx.rotate(layer*1.9);
        ctx.beginPath();ctx.arc(0,0,radius,0,Math.PI*2);ctx.strokeStyle=`rgba(77,226,215,${.09-layer*.018})`;ctx.lineWidth=1.1;ctx.setLineDash([7,16]);ctx.stroke();ctx.restore();
      }
      ctx.restore();
      for(const p of pulses){p.a+=p.s*dt; const r=Math.min(W,H)*p.r; const x=W/2+Math.cos(p.a)*r; const y=H*.52+Math.sin(p.a)*r*.32;
        ctx.beginPath();ctx.arc(x,y,2.2,0,Math.PI*2);ctx.fillStyle='rgba(120,255,241,.8)';ctx.fill();
      }
    }
    raf=requestAnimationFrame(draw);
  };
  raf=requestAnimationFrame(draw);
}
function mountPointerFX(){
  const root=document.documentElement;
  const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const pointer=e=>{root.style.setProperty('--mx',(e.clientX/innerWidth*100).toFixed(2)+'%');root.style.setProperty('--my',(e.clientY/innerHeight*100).toFixed(2)+'%');root.style.setProperty('--cursor-x',e.clientX+'px');root.style.setProperty('--cursor-y',e.clientY+'px');};
  if(!root.dataset.pointerBound){addEventListener('pointermove',pointer,{passive:true});root.dataset.pointerBound='1'}
  if(reduce)return;
  document.querySelectorAll('.role-card,.feature-grid article,.metric,.panel,.login-card,.access-panel,.float-card').forEach(el=>{
    if(el.dataset.tiltBound)return; el.dataset.tiltBound='1';
    el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.setProperty('--rx',(-y*6).toFixed(2)+'deg');el.style.setProperty('--ry',(x*8).toFixed(2)+'deg');el.style.setProperty('--lift','-6px')},{passive:true});
    el.addEventListener('pointerleave',()=>{el.style.setProperty('--rx','0deg');el.style.setProperty('--ry','0deg');el.style.setProperty('--lift','0px')},{passive:true});
  });
  document.querySelectorAll('button,.primary,.danger,.glass-btn').forEach(btn=>{
    if(btn.dataset.fxBound)return;btn.dataset.fxBound='1';btn.classList.add('ripple');
    btn.addEventListener('click',e=>{const r=btn.getBoundingClientRect(),dot=document.createElement('i');dot.className='ripple-dot';const size=Math.max(r.width,r.height)*.42;dot.style.width=dot.style.height=size+'px';dot.style.left=(e.clientX-r.left-size/2)+'px';dot.style.top=(e.clientY-r.top-size/2)+'px';btn.appendChild(dot);setTimeout(()=>dot.remove(),720)},{passive:true});
  });
  const reveal=()=>{const items=document.querySelectorAll('.feature-grid article,.role-card,.metric,.panel,.login-card,.access-panel,.split');items.forEach(el=>{if(!el.classList.contains('reveal-ready'))el.classList.add('reveal-ready')});if(!window.IntersectionObserver)return;const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('revealed');io.unobserve(x.target)}}),{threshold:.08});items.forEach(x=>io.observe(x));};
  reveal();
}
function announcePage(){if(state.disability==='blind')setTimeout(()=>speak(document.body.innerText.replace(/\s+/g,' ').slice(0,1400)),220)}

window.addEventListener('hashchange',render);
mountVisualFX();
render();
setTimeout(mountPointerFX,120);
